<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\MenuItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::pluck('id', 'slug');

        foreach ($this->menuItems() as $item) {
            $categorySlug = $item['category_slug'] ?? null;
            unset($item['category_slug']);

            $slug = $item['slug'] ?? Str::slug($item['name']);
            $imageUrl = $item['image_url'] ?? null;
            unset($item['image_url'], $item['slug']);

            MenuItem::updateOrCreate(
                ['slug' => $slug],
                array_merge($item, [
                    'slug' => $slug,
                    'category_id' => $categorySlug ? ($categories[$categorySlug] ?? null) : null,
                    'image_url' => $imageUrl,
                ])
            );
        }
    }

    private function menuItems(): array
    {
        return [
            // bento-boxes
            [
                'name' => 'Beef Sukiyaki',
                'slug' => 'beef-sukiyaki',
                'description' => 'Thinly sliced beef in sweet soy sauce',
                'price' => 329,
                'calories' => 600,
                'image_url' => 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Beef Teriyaki',
                'slug' => 'beef-teriyaki',
                'description' => 'Tender beef with savory teriyaki sauce',
                'price' => 0,
                'calories' => 600,
                'image_url' => 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&h=800&fit=crop&q=80',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Character/Decorative Bento (Kyaraben)',
                'slug' => 'characterdecorative-bento-kyaraben',
                'description' => 'Bento designed with creative food art (characters or cute shapes), especially popular for kids',
                'price' => 299,
                'calories' => 620,
                'image_url' => 'https://static1.squarespace.com/static/6217a6968b376a434418ae8b/t/6416043616fc5e2dca82c202/1679164471002/Show%2BYour%2BLove%2Bwith%2Bour%2BMiso%2BTasty%2BBento%2BBox%2BLunch%2BIdeas.jpg?format=1500w',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Chicken Katsu',
                'slug' => 'chicken-katsu',
                'description' => 'Breaded and fried chicken cutlet',
                'price' => 0,
                'calories' => 600,
                'image_url' => 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800&h=800&fit=crop&q=80',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Custom Bento Box (4 compartments)',
                'slug' => 'custom-bento-box-4-compartments',
                'description' => 'Build your own bento! Choose your main dish and 3 side dishes to create your perfect meal',
                'price' => 399,
                'calories' => 650,
                'image_url' => 'https://imgs.search.brave.com/S0T1nmKYFVTVl1hkaTsZtSe683birb4nbOomIMnP9W8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdDQu/ZGVwb3NpdHBob3Rv/cy5jb20vMTAwMTAz/My8zNzg4OC9pLzQ1/MC9kZXBvc2l0cGhv/dG9zXzM3ODg4OTI3/MC1zdG9jay1waG90/by1qYXBhbmVzZS1z/dHlsZS1sdW5jaC1i/ZW50by1ib3guanBn',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Makunouchi Bento',
                'slug' => 'makunouchi-bento',
                'description' => 'A classic, well-balanced lunch box with rice, grilled fish, egg, pickles, and side dishes',
                'price' => 329,
                'calories' => 580,
                'image_url' => 'https://www.webstaurantstore.com/uploads/blog/2023/1/bento-box_what-is-bento.jpg',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Salmon Grilled',
                'slug' => 'salmon-grilled',
                'description' => 'Fresh grilled salmon fillet',
                'price' => 0,
                'calories' => 600,
                'image_url' => 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=800&fit=crop&q=80',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Salmon Sashimi Set w/ Rice & Salad',
                'slug' => 'salmon-sashimi-set-w-rice-salad',
                'description' => 'Fresh salmon sashimi slices with sushi rice, wasabi, pickled ginger, and fresh garden salad',
                'price' => 369,
                'calories' => 480,
                'image_url' => 'https://imgs.search.brave.com/4XEfjs2MioWxPZde9D7540xDohQU74BhbpSAY1aMetc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jb29r/d2l0aGRhbmEuY29t/L3dwLWNvbnRlbnQv/dXBsb2Fkcy8yMDIy/LzA2L0lNR184OTI3/LTc2OHgxMDI0Lmpw/Zw',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Salmon Teriyaki',
                'slug' => 'salmon-teriyaki',
                'description' => 'Fresh salmon with teriyaki glaze',
                'price' => 289,
                'calories' => 600,
                'image_url' => 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Spring Rolls (2 pcs)',
                'slug' => 'spring-rolls',
                'description' => 'Crispy vegetable spring rolls',
                'price' => 0,
                'calories' => 300,
                'image_url' => null,
                'type' => 'side',
                'category_slug' => 'bento-boxes',
                'is_available' => false,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Takoyaki (3 pcs)',
                'slug' => 'takoyaki',
                'description' => 'Octopus balls with savory sauce',
                'price' => 0,
                'calories' => 600,
                'image_url' => null,
                'type' => 'side',
                'category_slug' => 'bento-boxes',
                'is_available' => false,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Teriyaki Chicken',
                'slug' => 'teriyaki-chicken',
                'description' => 'Grilled chicken glazed with sweet teriyaki sauce',
                'price' => 249,
                'calories' => 600,
                'image_url' => 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Teriyaki Chicken Bento w/ Miso Soup',
                'slug' => 'teriyaki-chicken-bento-w-miso-soup',
                'description' => 'Grilled chicken glazed with sweet teriyaki sauce, served with steamed rice, miso soup, and pickled vegetables',
                'price' => 249,
                'calories' => 620,
                'image_url' => 'https://imgs.search.brave.com/ie4McayudV0J8A27AjImXfd9rfnYd-IJKgzJ92jLryE/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/bW9zaGkta29zaGku/Y29tL2Nkbi9zaG9w/L3Byb2R1Y3RzL0No/aWNrZW50ZXJleWFr/aV9CRU5UT2NvcHlf/NTAzeDUwMy5wbmc_/dj0xNjA3MDEzNjI4',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Tonkatsu',
                'slug' => 'tonkatsu',
                'description' => 'Crispy breaded pork cutlet',
                'price' => 0,
                'calories' => 600,
                'image_url' => 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&h=800&fit=crop&q=80',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Tonkatsu Pork',
                'slug' => 'tonkatsu-pork',
                'description' => 'Breaded and fried pork cutlet',
                'price' => 279,
                'calories' => 600,
                'image_url' => 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=600&h=600&fit=crop',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Tonkatsu Pork Cutlet w/ Curry Rice',
                'slug' => 'tonkatsu-pork-cutlet-w-curry-rice',
                'description' => 'Crispy breaded pork cutlet served with Japanese curry sauce over steamed rice and shredded cabbage',
                'price' => 299,
                'calories' => 750,
                'image_url' => 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Traditional Japanese Bento Box',
                'slug' => 'traditional-japanese-bento-box',
                'description' => 'A set with assorted foods such as sushi, tempura, and sides packed in wooden or lacquered compartments',
                'price' => 349,
                'calories' => 600,
                'image_url' => 'https://www.enso.jp/cdn/shop/articles/Japanese-Bento_800x.jpg?v=1658724848',
                'type' => 'main',
                'category_slug' => 'bento-boxes',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],

            // sushi
            [
                'name' => 'California Roll',
                'slug' => 'california-roll',
                'description' => 'Crab (or imitation crab), avocado, cucumber, rice on the outside',
                'price' => 189,
                'calories' => 280,
                'image_url' => 'https://imgs.search.brave.com/Rf6rtnvMZ1gY54RAyPy8ps9_A4PnSNq22-SoHTQttn0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aGVz/Y2htaWR0eXdpZmUu/Y29tL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDIxLzAyL0Nob3Bz/dGlja19DYWxpZm9y/bmlhX1JvbGxzLTY4/M3gxMDI0LmpwZw',
                'type' => 'main',
                'category_slug' => 'sushi',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'California Roll (8 pcs)',
                'slug' => 'california-roll-8-pcs',
                'description' => 'Imitation crab, avocado, and cucumber wrapped in seasoned rice and nori seaweed',
                'price' => 189,
                'calories' => 280,
                'image_url' => 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'sushi',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Dragon Roll (8 pcs)',
                'slug' => 'dragon-roll-8-pcs',
                'description' => 'Shrimp tempura and cucumber inside, topped with sliced avocado and eel sauce drizzle',
                'price' => 269,
                'calories' => 340,
                'image_url' => 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'sushi',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Rainbow Roll',
                'slug' => 'rainbow-roll',
                'description' => 'California roll topped with tuna, salmon, and other fish',
                'price' => 299,
                'calories' => 360,
                'image_url' => 'https://imgs.search.brave.com/gaZB9oYufH8ztNGhjMdncRoEPKwTmPvzzc1r1CPaTP4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5nZXR0eWltYWdl/cy5jb20vaWQvMTM1/OTM0NzY5MS9waG90/by9qYXBhbmVzZS1w/bGF0dGVyLW9mLXJh/aW5ib3ctcm9sbHMt/bWFraS1pbnNpZGUt/b3V0LXNlYXdlZWQt/YW5kLXJpY2Utcm9s/bC5qcGc_cz02MTJ4/NjEyJnc9MCZrPTIw/JmM9akl4UUdjSWhz/YUJIOWhtb0Y1UllC/SkNpTVhyVWxNeHBG/bGZuaElzU1JkQT0',
                'type' => 'main',
                'category_slug' => 'sushi',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Spicy Tuna Roll',
                'slug' => 'spicy-tuna-roll',
                'description' => 'Tuna mixed with spicy mayo, rolled with rice and seaweed',
                'price' => 219,
                'calories' => 310,
                'image_url' => 'https://imgs.search.brave.com/CLuA-0y5YAHx8ZRx4EmXC7n2eAjsqn6hf9jECXpIUmo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aGVk/ZWxpY2lvdXNsaWZl/LmNvbS93cC1jb250/ZW50L3VwbG9hZHMv/MjAyMy8wMS9zcGlj/eXQtdHVuYS1yb2xs/LXBpZWNlLWNob3Bz/dGlja3MuanBn',
                'type' => 'main',
                'category_slug' => 'sushi',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Spicy Tuna Roll (8 pcs)',
                'slug' => 'spicy-tuna-roll-8-pcs',
                'description' => 'Fresh tuna mixed with spicy mayo, cucumber, topped with sesame seeds and spicy sauce',
                'price' => 219,
                'calories' => 310,
                'image_url' => 'https://images.unsplash.com/photo-1617196035102-f0d30134f1c7?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'sushi',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],

            // ramen
            [
                'name' => 'Miso Ramen',
                'slug' => 'miso-ramen',
                'description' => 'Hearty miso-based ramen with rich, umami flavor',
                'price' => 269,
                'calories' => 540,
                'image_url' => 'https://inquiringchef.com/wp-content/uploads/2022/11/Easy-Miso-Ramen-0723-1097x1536.jpg',
                'type' => 'main',
                'category_slug' => 'ramen',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Shio Ramen',
                'slug' => 'shio-ramen',
                'description' => 'Light and clear salt-based ramen broth, delicate and refreshing',
                'price' => 239,
                'calories' => 480,
                'image_url' => 'https://imgs.search.brave.com/ql6Efl73vIBnkRrbZjX2zFI4hIOl394KK6U4y02qxLQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTc0/MzQxNjkyMC9waG90/by9zaGlvLXJhbWVu/LmpwZz9zPTYxMng2/MTImdz0wJms9MjAm/Yz1zMTdfdmJEalZQ/Q1dBTTM2NkpEX2Vs/Y1VQNzMxcldnMm42/eU5CM2VFSVZzPQ',
                'type' => 'main',
                'category_slug' => 'ramen',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Shoyu Ramen',
                'slug' => 'shoyu-ramen',
                'description' => 'Classic soy sauce based ramen with rich, savory broth',
                'price' => 249,
                'calories' => 520,
                'image_url' => 'https://www.justonecookbook.com/wp-content/uploads/2023/04/Shoyu-Ramen-8285-II-800x1200.jpg',
                'type' => 'main',
                'category_slug' => 'ramen',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Spicy Miso Ramen',
                'slug' => 'spicy-miso-ramen',
                'description' => 'Hearty miso broth with spicy chili oil, ground pork, corn, bean sprouts, and nori seaweed',
                'price' => 269,
                'calories' => 560,
                'image_url' => 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'ramen',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Tonkotsu Ramen',
                'slug' => 'tonkotsu-ramen',
                'description' => 'Rich and creamy pork bone broth ramen, deeply flavorful',
                'price' => 279,
                'calories' => 680,
                'image_url' => 'https://imgs.search.brave.com/m2Gq-OyZHpBzNtsNYcuq5lqRXoiHEEjcSarz1GZgkAM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/anVzdG9uZWNvb2ti/b29rLmNvbS93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyNS8wNS9F/YXN5LVRvbmtvdHN1/LVJhbWVuLVJlY2lw/ZS0yNi0xMjAweDQw/NS5qcGc',
                'type' => 'main',
                'category_slug' => 'ramen',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Vegetable Ramen',
                'slug' => 'vegetable-ramen',
                'description' => 'Light vegetable broth with seasonal vegetables, tofu, mushrooms, and sesame oil',
                'price' => 229,
                'calories' => 420,
                'image_url' => 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'ramen',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],

            // drinks
            [
                'name' => 'Calpico (Calpis)',
                'slug' => 'calpico-calpis',
                'description' => 'Refreshing Japanese yogurt-based soft drink, sweet and tangy',
                'price' => 89,
                'calories' => 120,
                'image_url' => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'drinks',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Japanese Green Tea',
                'slug' => 'japanese-green-tea',
                'description' => 'Hot or iced premium Japanese green tea, refreshing and healthy',
                'price' => 89,
                'calories' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'drinks',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Japanese Iced Coffee',
                'slug' => 'japanese-iced-coffee',
                'description' => 'Cold brew coffee Japanese style, smooth and refreshing',
                'price' => 119,
                'calories' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'drinks',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Katsudon (Pork Cutlet Bowl)',
                'slug' => 'katsudon-pork-cutlet-bowl',
                'description' => 'Crispy pork cutlet and onions simmered in sweet soy sauce with fluffy egg over rice',
                'price' => 249,
                'calories' => 780,
                'image_url' => 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'drinks',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Matcha Latte',
                'slug' => 'matcha-latte',
                'description' => 'Creamy matcha green tea latte, sweetened and served hot or iced',
                'price' => 129,
                'calories' => 180,
                'image_url' => 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'drinks',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Ramune (Japanese Soda)',
                'slug' => 'ramune-japanese-soda',
                'description' => 'Classic Japanese carbonated soft drink with marble stopper, various flavors available',
                'price' => 99,
                'calories' => 90,
                'image_url' => 'https://imgs.search.brave.com/0DlutQoXk_IsYXdyRNEAIi5ufEedAS3Y9h2iJNA58PM/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aHVt/YnMuZHJlYW1zdGlt/ZS5jb20vYi9yYW11/bmUtJUMzJUEzJUM2/JTkyJUMyJUE5JUMz/JUEzJUM2JTkyLSVD/MyVBMyVDNiU5MiVD/MiU4RC1tdXN0LWRy/aW5rLWJldmVyYWdl/LWNzdW1tZXItdHlw/ZS1jYXJib25hdGVk/LXNvZnQtb3JpZ2lu/YWxseS1jcmVhdGVk/LXNvbGQtamFwYW4t/MTE3NDY4MzMzLmpwZw',
                'type' => 'main',
                'category_slug' => 'drinks',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Sake (Hot/Cold)',
                'slug' => 'sake-hotcold',
                'description' => 'Traditional Japanese rice wine',
                'price' => 199,
                'calories' => 110,
                'image_url' => 'https://imgs.search.brave.com/eEHByITqOoS5ob37HJfSjF9Mfk89EqCXXSrRguubTt4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/amFwYW4tZ3VpZGUu/Y29tL2cyMS8yMDM3/X3Nha2VfMDUuanBn',
                'type' => 'main',
                'category_slug' => 'drinks',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Umeshu (Plum Wine)',
                'slug' => 'umeshu-plum-wine',
                'description' => 'Sweet Japanese plum wine, served on the rocks or straight',
                'price' => 179,
                'calories' => 130,
                'image_url' => 'https://imgs.search.brave.com/wyCO18XyQjD8tcjUyRUi_1sHu8iTpeWfBNrFJpEf23o/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/c2hvcGlmeS5jb20v/cy9maWxlcy8xLzEw/ODMvMjYxMi9maWxl/cy91bWVzaHU4XzQ4/MHg0ODAuanBnP3Y9/MTczNjIyMjI5OA',
                'type' => 'main',
                'category_slug' => 'drinks',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Una Don (Eel Bowl)',
                'slug' => 'una-don-eel-bowl',
                'description' => 'Grilled freshwater eel glazed with sweet kabayaki sauce over rice with sesame seeds',
                'price' => 349,
                'calories' => 670,
                'image_url' => 'https://images.unsplash.com/photo-1582450871972-ab5ca641643d?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'drinks',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Yuzu Lemonade (fresh lemon)',
                'slug' => 'yuzu-lemonade-fresh-lemon',
                'description' => 'Fresh yuzu citrus lemonade, tangy and refreshing and so good',
                'price' => 119,
                'calories' => 95,
                'image_url' => 'https://imgs.search.brave.com/sJo_57kovk1hZnQGyHQAqpDi1dfiKXDzb778sUrut9A/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lbWls/eWxhdXJhZS5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMjMv/MDcveXV6dS1sZW1v/bmFkZS04LmpwZw',
                'type' => 'main',
                'category_slug' => 'drinks',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],

            // appetizers
            [
                'name' => 'Agedashi Tofu',
                'slug' => 'agedashi-tofu',
                'description' => 'Deep-fried tofu cubes in a light dashi broth, topped with grated daikon, green onions, and bonito flakes',
                'price' => 119,
                'calories' => 180,
                'image_url' => 'https://www.justonecookbook.com/wp-content/uploads/2022/06/Agedashi-Tofu-8416-I-2.jpg',
                'type' => 'main',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Chicken Karaage',
                'slug' => 'chicken-karaage',
                'description' => 'Japanese-style fried chicken marinated in soy sauce, ginger, and garlic, crispy and juicy',
                'price' => 149,
                'calories' => 420,
                'image_url' => 'https://imgs.search.brave.com/Fd2UDpAq1sb_cZ2tNaI7O785dH6-sEmlWq-RtK8eCCw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y2hvcHN0aWNrY2hy/b25pY2xlcy5jb20v/d3AtY29udGVudC91/cGxvYWRzLzIwMTkv/MDgvS2FyYWFnZS11/cGRhdGUtMzItMTAy/NHg2ODMuanBn',
                'type' => 'main',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Edamame',
                'slug' => 'edamame',
                'description' => 'Steamed soybeans with salt',
                'price' => 0,
                'calories' => 250,
                'image_url' => 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
                'type' => 'side',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Gyoza',
                'slug' => 'gyoza',
                'description' => 'Pan-fried Japanese dumplings',
                'price' => 0,
                'calories' => 250,
                'image_url' => 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
                'type' => 'side',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Gyoza (3 pcs)',
                'slug' => 'gyoza-3-pcs',
                'description' => 'Pan-fried dumplings',
                'price' => 0,
                'calories' => 180,
                'image_url' => 'https://popmenucloud.com/cdn-cgi/image/width%3D1200%2Cheight%3D1200%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/sixorbhq/ca2369b3-25f6-4c02-85bb-de8a7b21feec.jpg',
                'type' => 'side',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Gyoza (3 pcs)',
                'slug' => 'gyoza-3-pcs-1',
                'description' => 'Pan-fried dumplings with side of soy sauce',
                'price' => 85,
                'calories' => 180,
                'image_url' => 'https://popmenucloud.com/cdn-cgi/image/width%3D1200%2Cheight%3D1200%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/sixorbhq/ca2369b3-25f6-4c02-85bb-de8a7b21feec.jpg',
                'type' => 'main',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Gyoza (6 pcs)',
                'slug' => 'gyoza-6-pcs',
                'description' => 'Pan-fried dumplings filled with seasoned pork and vegetables, served with ponzu dipping sauce',
                'price' => 129,
                'calories' => 240,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVAiXyA_8ZV6XUPSY0ytqoJqg2JkZbAhTi6g&s',
                'type' => 'main',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Miso Soup',
                'slug' => 'miso-soup',
                'description' => 'Traditional Japanese miso soup',
                'price' => 0,
                'calories' => 250,
                'image_url' => 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
                'type' => 'side',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Pickled Vegetables',
                'slug' => 'pickled-vegetables',
                'description' => 'Traditional Japanese pickles',
                'price' => 0,
                'calories' => 250,
                'image_url' => 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
                'type' => 'side',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Salad',
                'slug' => 'salad',
                'description' => 'Fresh garden salad with Japanese dressing',
                'price' => 0,
                'calories' => 250,
                'image_url' => 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
                'type' => 'side',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Shrimp Tempura (5 pcs)',
                'slug' => 'shrimp-tempura-5-pcs',
                'description' => 'Large tiger prawns coated in crispy tempura batter, served with grated daikon and sauce',
                'price' => 249,
                'calories' => 360,
                'image_url' => 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Takoyaki (6 pcs)',
                'slug' => 'takoyaki-6-pcs',
                'description' => 'Crispy octopus balls topped with takoyaki sauce, Japanese mayo, bonito flakes, and seaweed',
                'price' => 149,
                'calories' => 280,
                'image_url' => 'https://www.finedininglovers.com/sites/default/files/recipe_content_images/takoyaki-recipe%C2%A9iStock.jpg',
                'type' => 'main',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Vegetable Tempura',
                'slug' => 'vegetable-tempura',
                'description' => 'Seasonal vegetables including sweet potato, eggplant, mushrooms, and green beans in light batter',
                'price' => 189,
                'calories' => 360,
                'image_url' => 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Yakitori (2 skewers)',
                'slug' => 'yakitori-2-skewers',
                'description' => 'Grilled chicken skewers glazed with sweet teriyaki sauce, tender and flavorful',
                'price' => 139,
                'calories' => 260,
                'image_url' => 'https://imgs.search.brave.com/Xr4FJ_BneN_TNhKY-o7SU34Z8x7GBs4m8xUoW3cZb4s/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90aHVt/YnMuZHJlYW1zdGlt/ZS5jb20vYi95YWtp/dG9yaS1vbmUtamFw/YW5lc2UtZGlzaGVz/LTczMDQyNjg0Lmpw/Zw',
                'type' => 'main',
                'category_slug' => 'appetizers',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],

            // desserts
            [
                'name' => 'Dorayaki',
                'slug' => 'dorayaki',
                'description' => 'Sweet red bean paste sandwiched between two fluffy pancakes',
                'price' => 99,
                'calories' => 220,
                'image_url' => 'https://imgs.search.brave.com/roamWBGDzjQPlpBta_g5DmKWJL-4VqhRy3sk8R7B3ZQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/Y3JlYXRlLnZpc3Rh/LmNvbS9hcGkvbWVk/aWEvc21hbGwvODA0/Nzg0NS9zdG9jay1w/aG90by1kb3JheWFr/aS1qYXBhbmVzZS1j/b25mZWN0aW9uZXJ5',
                'type' => 'dessert',
                'category_slug' => 'desserts',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Green Tea',
                'slug' => 'green-tea',
                'description' => 'Hot or iced Japanese green tea',
                'price' => 0,
                'calories' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&h=800&fit=crop&q=80',
                'type' => 'drink',
                'category_slug' => 'desserts',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Iced Coffee',
                'slug' => 'iced-coffee',
                'description' => 'Cold brew Japanese coffee',
                'price' => 0,
                'calories' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&h=800&fit=crop&q=80',
                'type' => 'drink',
                'category_slug' => 'desserts',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Matcha Ice Cream',
                'slug' => 'matcha-ice-cream',
                'description' => 'Creamy green tea ice cream with authentic matcha flavor',
                'price' => 129,
                'calories' => 190,
                'image_url' => 'https://imgs.search.brave.com/EWNKwdKkLy8Qm4Y60GxT1yI33NuRl8RWoZsdsnPUT6M/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMuc3F1YXJlc3Bh/Y2UtY2RuLmNvbS9j/b250ZW50L3YxLzUz/M2Y1ODRmZTRiMGY3/N2UxYmQyZTRkMS8x/NjE5NDk2OTU2ODk4/LVBER1paNjBRQ0pF/MkYyRzVSMkozL01h/dGNoYStJY2UrQ3Jl/YW0wMDI1LmpwZw',
                'type' => 'dessert',
                'category_slug' => 'desserts',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Mochi',
                'slug' => 'mochi',
                'description' => 'Soft and chewy Japanese rice cake with sweet filling',
                'price' => 89,
                'calories' => 150,
                'image_url' => 'https://imgs.search.brave.com/oInvuGxOAgkeSC6-Re3vUNpt1QPw7NjfyDEXefv1Rb8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdGF0/aWMudmVjdGVlenku/Y29tL3N5c3RlbS9y/ZXNvdXJjZXMvdGh1/bWJuYWlscy8wNDgv/MDcxLzA5NC9zbWFs/bC9kZWxpY2lvdXMt/c3dlZXQtY2hpbGxl/ZC1tb2NoaS1kZXNz/ZXJ0cy13aXRoLWZy/dWl0LWZpbGxpbmct/cGhvdG8uSlBH',
                'type' => 'dessert',
                'category_slug' => 'desserts',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Spring Rolls (4 pcs)',
                'slug' => 'spring-rolls-4-pcs',
                'description' => 'Crispy vegetable spring rolls filled with cabbage, carrots, and glass noodles with sweet chili sauce',
                'price' => 119,
                'calories' => 200,
                'image_url' => 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=800&q=80',
                'type' => 'main',
                'category_slug' => 'desserts',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Taiyaki',
                'slug' => 'taiyaki',
                'description' => 'Fish-shaped cake filled with sweet red bean paste or custard',
                'price' => 109,
                'calories' => 210,
                'image_url' => 'https://imgs.search.brave.com/BKxUYzENokfWU4rZOKBL5kehiaM69mqHYoziZz2WXM4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMjE1/Mzg5Nzg1Mi9waG90/by9qYXBhbmVzZS1z/d2VldHMtdGFpeWFr/aS5qcGc_cz02MTJ4/NjEyJnc9MCZrPTIw/JmM9eDhvVkxJWDNs/andnMDVCV0o1a3py/N3I1ZUZjaDRFYnVP/NFdoR3I5VUNGbz0',
                'type' => 'dessert',
                'category_slug' => 'desserts',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => true,
            ],

            // tempura
            [
                'name' => 'Ebi Tempura',
                'slug' => 'ebi-tempura',
                'description' => 'Tempura made with jumbo shrimp/prawns — long, crunchy, and classic. Often served with a dipping sauce (tentsuyu) and grated daikon',
                'price' => 249,
                'calories' => 380,
                'image_url' => 'https://imgs.search.brave.com/JH9IANCIxWFHvToSULdpiUERgamm1kagHSjfDOOjy9k/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzE0LzY2LzM5Lzcx/LzM2MF9GXzE0NjYz/OTcxNDFfdlFRRHQ5/WFBzRk9IeTVJT21h/MzAyYUZQVHN4R3oy/bnouanBn',
                'type' => 'main',
                'category_slug' => 'tempura',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Kisu Tempura (Japanese Whiting)',
                'slug' => 'kisu-tempura-japanese-whiting',
                'description' => 'Tempura made with kisu, a mild white fish — delicate and light, with a super crispy coating',
                'price' => 229,
                'calories' => 350,
                'image_url' => 'https://imgs.search.brave.com/AZUP7RcQJa700ZqSMPEo9ZLn9qyCkv7iLVakbGtYiug/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMueXVtbXkucGgv/eXVtbXkvdXBsb2Fk/cy8yMDE4LzAzL0Fz/b2hvc19UZW1wdXJh/LURhaXJ5X0Rhcmls/YWctMS5qcGc',
                'type' => 'main',
                'category_slug' => 'tempura',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Tempura Vegetables',
                'slug' => 'tempura-vegetables',
                'description' => 'Assorted vegetables in tempura batter',
                'price' => 0,
                'calories' => 360,
                'image_url' => 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&w=300&h=300&fit=crop',
                'type' => 'side',
                'category_slug' => 'tempura',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Yasai Tempura (Vegetable Tempura)',
                'slug' => 'yasai-tempura-vegetable-tempura',
                'description' => 'A mix of vegetables such as sweet potato, eggplant, bell pepper, pumpkin, and green beans lightly battered and fried until crisp and golden',
                'price' => 189,
                'calories' => 320,
                'image_url' => 'https://imgs.search.brave.com/lsiEeS8a6liFZA542OBq6zL_-RdczAS35AoXiRe1WUA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/anVzdG9uZWNvb2ti/b29rLmNvbS93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyMC8wNS9W/ZWdldGFibGUtVGVt/cHVyYS0xNzA2LUlW/LmpwZw',
                'type' => 'main',
                'category_slug' => 'tempura',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => false,
            ],

            // donburi
            [
                'name' => 'Gyūdon (Beef Bowl)',
                'slug' => 'gyudon-beef-bowl',
                'description' => 'Thinly sliced beef simmered in sweet soy sauce over steamed rice',
                'price' => 229,
                'calories' => 720,
                'image_url' => 'https://imgs.search.brave.com/SanaFoOnNC3bKGVEqgS09RWQ70MCH3g82l9DO8BtLZY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdWRh/Y2hpcmVjaXBlcy5j/b20vd3AtY29udGVu/dC91cGxvYWRzLzIw/MjAvMDMvZ3l1ZG9u/LXNxLTU1MHg1NTAu/cG5n',
                'type' => 'main',
                'category_slug' => 'donburi',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Oyakodon (Chicken & Egg Bowl)',
                'slug' => 'oyakodon-chicken-egg-bowl',
                'description' => 'Tender chicken and onions cooked with egg in savory dashi broth over steamed rice',
                'price' => 219,
                'calories' => 650,
                'image_url' => 'https://imgs.search.brave.com/RiCJpcIDHYr70DegyDlQ2rUaFd8IxRZSvjbqsu5EX1c/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/anVzdG9uZWNvb2ti/b29rLmNvbS93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyMi8xMC9P/eWFrb2Rvbi0wNjEz/LUkuanBn',
                'type' => 'main',
                'category_slug' => 'donburi',
                'is_available' => true,
                'is_featured' => true,
                'is_bestseller' => false,
            ],
            [
                'name' => 'Unadon (Eel Bowl) (spicy)',
                'slug' => 'unadon-eel-bowl-spicy',
                'description' => 'Grilled freshwater eel glazed with rich, sweet soy sauce (kabayaki) and served on steamed rice. and so so good',
                'price' => 300,
                'calories' => 680,
                'image_url' => 'https://imgs.search.brave.com/CZRBZ4RYucrj7bmmEsm3GmbxjKSWI7WWGHtD6PtPaV8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/anVzdG9uZWNvb2ti/b29rLmNvbS93cC1j/b250ZW50L3VwbG9h/ZHMvMjAyMS8wNy9V/bmFkb24tRWVsLVJp/Y2UtOTUzMy1JSS5q/cGc',
                'type' => 'main',
                'category_slug' => 'donburi',
                'is_available' => true,
                'is_featured' => false,
                'is_bestseller' => true,
            ],
        ];
    }
}
